### ISSUE TITLE
Inherit with spring

### ISSUE THREAD

**Issue by cshuig** [RTBHOUSE/kafka-workers#17]
hi， Do you have plans to provide inheritance with spring?

**Comment by barteklos** [comment]
What exactly do you have in mind? Do you need any kind of compatibility with Spring Framework to use our library?

**Comment by cshuig** [comment]
The kafka worker integrates with spring and simplifies the use of annotations.

**Comment by cshuig** [comment]
none

**Comment by barteklos** [comment]
I am sorry for the lack of response. We do not have plans to support any DI framework at the moment. We would like to keep kafka-workers as light as possible so we provide it directly in our processing apps (we use google guice for this purposes).
