### ISSUE TITLE
Memory heavy RecordStatusObserverImpl

### ISSUE THREAD

**Issue by tulinski** [RTBHOUSE/kafka-workers#20]
There are two optimizations which should substantially improve memory footprint of RecordStatusObserverImpl instances:
1) Each RecordStatusObserverImpl instance keeps WorkerSubpartition which is created based on WorkerRecord. WorkerSubpartition instances are from a small set of values (#TopicPartitions * #subpartitions) and should be shared among RecordStatusObserverImpl instances. Currently WorkerSubpartition takes ~50% of RecordStatusObserverImpls' retained heap size.
2) Some fields of RecordStatusObserverImpl are globaly equal singletons, which could be kept as a single reference.

**Comment by tulinski** [comment]
I'm preparing a pull request implementing the above optimizations.

**Comment by barteklos** [comment]
+1 (I could not agree more) 

take a look on this pull request: https://github.com/barteklos/kafka-workers/pull/2/commits/ad5649287de9c0d736057aab56e2d470b72b9f58

**Comment by barteklos** [comment]
Done and available since 1.0.12-SNAPSHOT
